# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: |
  (?x)^(
    (.*/)?\.xmake/.+|
    (.*/)?build/.+|
    \.vscode/.+|
    (.*/)?\.luarc.json|
  )$
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
      - id: check-json
      - id: check-toml
      - id: check-yaml
        exclude: ^(.clang-format)$
      - id: end-of-file-fixer
      - id: trailing-whitespace
  # - repo: https://github.com/Koihik/LuaFormatter.git
  #   rev: 29afe1046ad015de96ffdb6d361a21882356e801
  #   hooks:
  #     - id: luaformatter
