add_requires("zlib v1.2.10", {system = false})
add_requires("zlib v1.2.13", {system = false})
add_requires("zlib v1.3", {system = false})
add_requires("zlib v1.3.1", {system = false})

target("main", function()
    set_kind("binary")
    add_files("main.cc")
    add_packages("zlib")
end)
