add_rules("mode.debug", "mode.release")
set_policy("test.return_zero_on_failure", true)

for _, file in ipairs(os.files("src/test_*.cpp")) do
    local name = path.basename(file)
    target(name, function()
        set_kind("binary")
        set_default(false)
        add_files("src/" .. name .. ".cpp")
        add_tests("default")
        add_tests("args", {runargs = {"foo", "bar"}})
        add_tests("pass_output", {trim_output = true, runargs = "foo", pass_outputs = "hello foo"})
        add_tests("fail_output", {fail_outputs = {"hello2 .*", "hello xmake"}})
    end)
end

target("test_10", function()
    set_kind("binary")
    set_default(false)
    add_files("src/compile_1.cpp")
    add_tests("compile_fail", {build_should_fail = true})
end)

target("test_11", function()
    set_kind("binary")
    set_default(false)
    add_files("src/compile_2.cpp")
    add_tests("compile_pass", {build_should_pass = true})
end)

target("test_13", function()
    set_kind("binary")
    set_default(false)
    add_files("src/test_1.cpp")
    add_tests("stub_1", {files = "tests/stub_1.cpp", defines = "STUB_1"})
end)

target("test_14", function()
    set_kind("binary")
    set_default(false)
    add_files("src/test_2.cpp")
    add_tests("stub_2", {files = "tests/stub_2.cpp", defines = "STUB_2"})
end)

target("test_15", function()
    set_kind("binary")
    set_default(false)
    add_files("src/test_1.cpp")
    add_tests("stub_n", {files = "tests/stub_n*.cpp", defines = "STUB_N"})
end)

target("test_timeout", function()
    set_kind("binary")
    set_default(false)
    add_files("src/run_timeout.cpp")
    add_tests("run_timeout", {run_timeout = 1000})
end)
