name: FreeBSD

on:
  pull_request:
  push:
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest

    concurrency:
        group: ${{ github.ref }}-${{ github.base_ref }}-${{ github.head_ref }}-FreeBSD
        cancel-in-progress: true
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Tests
        uses: vmactions/freebsd-vm@v1
        with:
          usesh: true
          mem: 4096
          copyback: false
          prepare: pkg install -y git curl unzip gmake llvm gsed bash perl5
          run: |
            ./configure
            gmake -j4
            gmake install
            xrepo --version
            export XMAKE_ROOT=y
            export XMAKE_MAIN_REPO=https://github.com/TOMO-CAT/xmake-repo.git
            export XMAKE_BINARY_REPO=https://github.com/TOMO-CAT/xmake-build-artifacts.git
            xmake l os.meminfo
            xmake lua -v -D tests/run.lua
