name: macOS (arm64)

on:
  pull_request:
  push:
    branches: [ master ]
  release:
    types: [published]

jobs:
  build:

    strategy:
      matrix:
        os: [macos-14]
        arch: [arm64]

    runs-on: ${{ matrix.os }}

    concurrency:
        group: ${{ github.ref }}-${{ github.base_ref }}-${{ github.head_ref }}-macOS-${{ matrix.arch }}
        cancel-in-progress: false
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true
      - name: Prepare local xmake
        run: cp -rf . ../xmake-source
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: local#../xmake-source

      - name: Tests
        env:
          XMAKE_ROOT: y
          XMAKE_MAIN_REPO: https://github.com/zxmake/zxmake-repo.git
          XMAKE_BINARY_REPO: https://github.com/zxmake/zxmake-build-artifacts.git
        run: |
          xmake lua -v -D tests/run.lua
          xrepo --version
